spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
  mongodb:
    uri: mongodb://sonny:sonny@localhost:27017/customer?authSource=admin
